name: run-python-tests-action
run-name: ${{ github.actor }} is running some python tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - run: python install pytest
      - run: pytest tests/
